naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: mW65xYEBd4hJLtkIqabB
    secret: yL_mccRohS

spring:
  devtools:
    liverload:
      enabled:true
    thymeleaf:
      cache:false